import { Inter , Roboto} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: ['100' , "300" ,"400" , "500"] , subsets: ["latin"] });

export const metadata = {
  title: "DoPractice ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar></Navbar>
        <div className="">
        {children}
        </div>
        <footer className="bg-red-500 px-7 py-10">
          <p>Copyright © 2023 Next Hero. All rights reserved.</p>
        </footer>
        </body>
    </html>
  );
}
