"use client";
import React, { useEffect, useState } from "react";
export const metadata = {
  title: "DoPractice ",
  description: "Generated by create next app",
};

const Meals = () => {
  const [search, setSearch] = useState("");
  const [meals, setMeals] = useState("");

  const loadData = async() => {
    const res = await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?f=${search}`)
    const data = await res.json();
    setMeals(data.meals);
  };
  const handler = (e) => {
    console.log(e.target.value);
    setSearch(e.target.value);
  };
  useEffect(() => {
    loadData();

  } , [search])

  return (
    <div className="m-12">
      <input
        onChange={handler}
        type="text"
        className="border-2 p-3 rounded-lg"
        placeholder="search meal"
      />
      <button onClick={() => loadData()} className="p-3 rounded-xl bg-red-600 text-white ">Search</button>
      <div className="mt-12 grid grid-cols-4 gap-8">
        {
            meals.map((meal) =>(<div key={meal?.idMeal} className="border-2 p-4">
                <h1>{meal.strMeal}</h1>
                <p>{meal.strInstructions}</p>
                
            </div>))
        }

      </div>
    </div>
  );
};

export default Meals;
